name: progLab
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - random
  - matplotlib
  - matplotlib.backends.backend_tkagg
  - seaborn
  - itertools
  - time
  - datetime
  - tqdm
  - os
  - argparse
  - tkinter
  - PIL
  - ttkthemes

